// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Yft6yLFq_HtMe0MrE76r0GbJiX_oRts',
    appId: '1:495455852830:web:bbae930e9dc090433f510f',
    messagingSenderId: '495455852830',
    projectId: 'report2-fac3d',
    authDomain: 'report2-fac3d.firebaseapp.com',
    storageBucket: 'report2-fac3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxA5ApNlx1PaA_H-nwkGI2lf87cV2x500',
    appId: '1:495455852830:android:78ca21f6923d26343f510f',
    messagingSenderId: '495455852830',
    projectId: 'report2-fac3d',
    storageBucket: 'report2-fac3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApudKy2T-sh1FJGV_439-Bygw5ruMwc7A',
    appId: '1:495455852830:ios:676eb7afa0c48d193f510f',
    messagingSenderId: '495455852830',
    projectId: 'report2-fac3d',
    storageBucket: 'report2-fac3d.appspot.com',
    iosClientId: '495455852830-prtdjf1ptvhqgb9sd19qfdgpfgq2fb5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReport2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApudKy2T-sh1FJGV_439-Bygw5ruMwc7A',
    appId: '1:495455852830:ios:676eb7afa0c48d193f510f',
    messagingSenderId: '495455852830',
    projectId: 'report2-fac3d',
    storageBucket: 'report2-fac3d.appspot.com',
    iosClientId: '495455852830-prtdjf1ptvhqgb9sd19qfdgpfgq2fb5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReport2',
  );
}
